config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do

  resources :products




  resources :categories

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == Settings.sidekiq.username && password == Settings.sidekiq.password
  end if Rails.env.production?
  mount Sidekiq::Web, at: '/sidekiq'

  concern :activeable do
    post :toggle_is_active, on: :member
  end

  # Admins
  devise_for :admins, controllers: { sessions: 'hq/sessions', registrations: 'hq/registrations', passwords: 'hq/passwords' }, path: 'hq',
             path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret',  confirmation: 'verification' }
  as :admin do
    get 'hq/edit' => 'hq/registrations#edit', as: 'edit_admin_registration'
    put 'hq' => 'hq/registrations#update', as: 'admin_registration'
  end
  namespace :hq do
    root to: 'dashboard#index'
    resources :dashboard, only: [:index]
    resources :admins, concerns: [:activeable]
    resources :users, concerns: [:activeable]
    resources :countries
    resources :cities
    resources :audits, only: [:index, :show]
    resources :brands
    resources :tags
    resources :products
    resources :categories

  end
  # Users
  devise_for :users, controllers: { sessions: 'user/sessions', registrations: 'user/registrations', passwords: 'user/passwords' }, path: 'user',
             path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret',  confirmation: 'verification' }
  as :user do
    get 'user/edit' => 'user/registrations#edit', as: 'edit_user_profile_registration'
    put 'user' => 'user/registrations#update', as: 'user_profile_registration'
  end
  namespace :user do
    root to: 'dashboard#index'
    resources :dashboard, only: [:index]
    resources :profile, only: [:show, :edit, :update]
  end

  # Common pages
  root to: 'welcome#index'

  if Rails.env.production? or Rails.env.staging?
    match '*unmatched_route', to: 'application#page_not_found', via: :all
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/views/welcome/index.html.haml
.jumbotron
  %h1 Welcome to Gigi
  - if current_user
    = link_to t('navbar.sign_out'), destroy_user_session_path, class: 'btn btn-large', method: :delete
    .row-fluid.marketing
      %p
        %strong Name:
        = current_user.name
      %p
        %strong Email:
        = current_user.email
    = link_to t('navbar.edit_login_info'), edit_user_registration_path, class: 'btn btn-large'
    = link_to t('navbar.profile'), user_profile_path(current_user), class: 'btn btn-link'
  - else
    = link_to t('navbar.signup'), new_user_registration_path, class: 'btn btn-large btn-success'
    = link_to t('navbar.signin'), new_user_session_path, class: 'btn btn-large'