config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do

  resources :products




  resources :categories

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == Settings.sidekiq.username && password == Settings.sidekiq.password
  end if Rails.env.production?
  mount Sidekiq::Web, at: '/sidekiq'

  concern :activeable do
    post :toggle_is_active, on: :member
  end

  # Admins
  devise_for :admins, controllers: { sessions: 'hq/sessions', registrations: 'hq/registrations', passwords: 'hq/passwords' }, path: 'hq',
             path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret',  confirmation: 'verification' }
  as :admin do
    get 'hq/edit' => 'hq/registrations#edit', as: 'edit_admin_registration'
    put 'hq' => 'hq/registrations#update', as: 'admin_registration'
  end
  namespace :hq do
    root to: 'dashboard#index'
    resources :dashboard, only: [:index]
    resources :admins, concerns: [:activeable]
    resources :users, concerns: [:activeable]
    resources :countries
    resources :cities
    resources :audits, only: [:index, :show]
    resources :brands
    resources :tags
    resources :products
    resources :categories

  end
  # Users
  devise_for :users, controllers: { sessions: 'user/sessions', registrations: 'user/registrations', passwords: 'user/passwords' }, path: 'user',
             path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret',  confirmation: 'verification' }
  as :user do
    get 'user/edit' => 'user/registrations#edit', as: 'edit_user_profile_registration'
    put 'user' => 'user/registrations#update', as: 'user_profile_registration'
  end
  namespace :user do
    root to: 'dashboard#index'
    resources :dashboard, only: [:index]
    resources :profile, only: [:show, :edit, :update]
  end

  # Common pages
  root to: 'welcome#index'

  if Rails.env.production? or Rails.env.staging?
    match '*unmatched_route', to: 'application#page_not_found', via: :all
  end

end

app/controllers/hq/admins_controller.rb
class Hq::AdminsController < Hq::ApplicationController

  before_action :set_admin, only: [:show, :edit, :update, :destroy, :toggle_is_active]
  add_breadcrumb I18n.t('activerecord.models.admins'), :hq_admins_path

  def index
    @search = Admin.order(id: :desc).search(params[:q])
    @admins = @search.result(distinct: true).paginate(page: params[:page])
    respond_with(@admins)
  end

  def show
    add_breadcrumb @admin.name, hq_admin_path(@admin)
    respond_with(@admin)
  end

  def new
    add_breadcrumb t('tooltips.new'), new_hq_admin_path
    @admin = Admin.new
    respond_with(@admin)
  end

  def edit
    add_breadcrumb @admin.name, hq_admin_path(@admin)
    add_breadcrumb t('tooltips.edit'), edit_hq_admin_path
  end

  def create
    @admin = Admin.new(admin_params)
    @admin.save
    respond_with(:hq, @admin)
  end

  def update
    @admin.update(admin_params)
    respond_with(:hq, @admin)
  end

  def destroy
    @admin.destroy
    respond_with(:hq, @admin, location: request.referer)
  end

  def toggle_is_active
    if @admin.update( is_active: !@admin.is_active )
      @admin.is_active ?
          flash[:info] = t('flash.actions.toggle_is_active.active', resource_name: Admin.model_name.human) :
          flash[:info] = t('flash.actions.toggle_is_active.passive', resource_name: Admin.model_name.human)
    else
      flash[:danger] = t('flash.messages.error_occurred')
    end
    respond_with(:hq, @admin, location: request.referer)
  end

  private

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def admin_params
    params.require(:admin).permit(:email, :name, :surname)
  end
end

app/controllers/hq/application_controller.rb
require 'application_responder'

class Hq::ApplicationController < ActionController::Base

  before_filter :set_audit_user
  before_action :authenticate_admin!

  self.responder = ApplicationResponder
  respond_to :html, :json

  private

  def set_audit_user
    # Set audit current user
    Audited.current_user_method = :current_admin
  end

end

app/controllers/hq/audits_controller.rb
class Hq::AuditsController < Hq::ApplicationController

  add_breadcrumb I18n.t('activerecord.models.audits'), :hq_audits_path

  def index
    @search = Audit.includes(:user).reorder('id DESC').search(params[:q])
    @audits = @search.result(distinct: true).paginate(page: params[:page])
    @auditable_types  = Audited::Adapters::ActiveRecord::Audit.select('auditable_type').group('auditable_type').reorder('')
  end

  def show
    @audit = Audit.find(params[:id])
    add_breadcrumb @audit.id, hq_audit_path(id: @audit)
  end

end

app/controllers/hq/brands_controller.rb
class Hq::BrandsController < Hq::ApplicationController

  before_action :get_brand, only: [:show, :edit, :update, :destroy]

  def index
    @brands = Brand.all
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)

    if @brand.save
      respond_with(:hq, @brand)
    else
      render 'new'
    end
  end

  def edit
    get_brand
  end

  def update
    get_brand

    if @brand.update(brand_params)
      respond_with(:hq, @brand)
    else
      render 'edit'
    end
  end

  def show
    get_brand
    @products = @brand.products
  end

  def destroy
    get_brand
    @brand.destroy
    redirect_to hq_brands_path
  end

  private

  def brand_params
    params.require(:brand).permit(:name)
  end

  def get_brand
    @brand = Brand.find(params[:id])
  end
end

app/controllers/hq/categories_controller.rb
class Hq::CategoriesController < Hq::ApplicationController
  def index
    @categories = Category.all
  end
  def new
    @category = Category.new

  end

  def create
    @category = Category.create(category_params)
    if @category.save
      respond_with(:hq,@category)
    else
      render 'new'
    end
  end
  def show
    @category = Category.find(params[:id])

  end
  def edit
    @category = Category.find(params[:id])
  end
  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      respond_with(:hq,@category)
    else
      render 'edit'
    end

  end
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to hq_categories_path
  end
  private
  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/hq/cities_controller.rb
class Hq::CitiesController < Hq::ApplicationController

  before_action :set_city, only: [:show, :edit, :update, :destroy]
  add_breadcrumb I18n.t('activerecord.models.cities'), :hq_cities_path

  def index
    @search = City.includes(:country).order(id: :desc).search(params[:q])
    @cities = @search.result(distinct: true).paginate(page: params[:page])
    respond_with(@cities)
  end

  def show
    add_breadcrumb @city.name, hq_city_path(@city)
    respond_with(@city)
  end

  def new
    add_breadcrumb t('tooltips.new'), new_hq_city_path
    @city = City.new
    respond_with(@city)
  end

  def edit
    add_breadcrumb @city.name, hq_city_path(@city)
    add_breadcrumb t('tooltips.edit'), edit_hq_city_path
  end

  def create
    @city = City.new(city_params)
    @city.save
    respond_with(:hq, @city)
  end

  def update
    @city.update(city_params)
    respond_with(:hq, @city)
  end

  def destroy
    @city.destroy
    respond_with(:hq, @city, location: request.referer)
  end

  private

  def city_params
    params.require(:city).permit(:name, :country_id)
  end

  def set_city
    @city = City.find(params[:id])
  end

end

app/controllers/hq/countries_controller.rb
class Hq::CountriesController < Hq::ApplicationController

  before_action :set_country, only: [:show, :edit, :update, :destroy]
  add_breadcrumb I18n.t('activerecord.models.countries'), :hq_countries_path

  def index
    @search = Country.order(id: :desc).search(params[:q])
    @countries = @search.result(distinct: true).paginate(page: params[:page])
    respond_with(@countries)
  end

  def show
    add_breadcrumb @country.name, hq_country_path(@country)
    respond_with(@country)
  end

  def new
    add_breadcrumb t('tooltips.new'), new_hq_country_path
    @country = Country.new
    respond_with(@country)
  end

  def edit
    add_breadcrumb @country.name, hq_country_path(@country)
    add_breadcrumb t('tooltips.edit'), edit_hq_country_path
  end

  def create
    @country = Country.new(country_params)
    @country.save
    respond_with(:hq, @country)
  end

  def update
    @country.update(country_params)
    respond_with(:hq, @country)
  end

  def destroy
    @country.destroy
    respond_with(:hq, @country, location: request.referer)
  end

  private

  def country_params
    params.require(:country).permit(:name)
  end

  def set_country
    @country = Country.find(params[:id])
  end

end

app/controllers/hq/dashboard_controller.rb
class Hq::DashboardController < Hq::ApplicationController

  add_breadcrumb I18n.t('dock.dashboard'), :hq_dashboard_index_path

  def index
  end

end

app/controllers/hq/passwords_controller.rb
class Hq::PasswordsController < Devise::PasswordsController
  layout 'hq/login'

  private

  def after_resetting_password_path_for(resource)
    hq_root_path
  end

end

app/controllers/hq/products_controller.rb
class Hq::ProductsController < Hq::ApplicationController
  def index
    @products = Product.all
  end
  def new
    @product = Product.new
    @categories = Category.all.map{ |c| [c.name, c.id] }
    @brands = Brand.all.map { |c| [c.name, c.id] }

  end
  def create
    @product = Product.new(product_params)
    @product.category_id = params[:category_id]
    @product.brand_id = params[:brand_id]
    if @product.save
      respond_with(:hq, @product)
    else
      render 'new'
    end

  end
  def show
    @product = Product.find(params[:id])
  end
  def edit
    @product = Product.find(params[:id])
    @categories = Category.all.map{ |c| [c.name, c.id] }
    @brands = Brand.all.map{ |c| [c.name, c.id]}


  end
  def update
    @product.category_id = params[:category_id]
    @product.brand_id = params[:brand_id]
    if @product.update(product_params)
      respond_with(:hq, @product)
      #redirect_to product_path(@product)
    else
      render 'edit'
    end
  end
  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      respond_with(:hq, @product)
    else
      render 'index'
    end
  end
  private
  def product_params
    params.require(:product).permit(:name, :description, :price, :category_id, :brand_id)
  end
end

app/controllers/hq/registrations_controller.rb
class Hq::RegistrationsController < Devise::RegistrationsController
  layout 'hq/application'
  before_action :authenticate_admin!
  before_action :redirect_admin, only: [:new, :create, :destroy]
  add_breadcrumb I18n.t('dock.dashboard'), :hq_dashboard_index_path

  def edit
    add_breadcrumb I18n.t('tt.edit', resource_name: Admin.model_name.human)
  end

  private

  def redirect_admin
    redirect_to hq_root_path
  end

  def after_update_path_for(resource)
    hq_root_path
  end

end

app/controllers/hq/sessions_controller.rb
class Hq::SessionsController < Devise::SessionsController
  layout 'hq/login'

  private

  # Overwriting the sign_out redirect path method
  def after_sign_in_path_for(resource_or_scope)
    hq_root_path
  end

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    new_admin_session_path
  end
  
end

app/controllers/hq/tags_controller.rb
class Hq::TagsController < Hq::ApplicationController

def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.create(tag_params)
    if @tag.save
      respond_with(:hq, @tag)
    else
      render 'new'
    end
  end

  def show
    @tag = Tag.find(params[:id])

  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])

    if @tag.update(category_params)
      respond_with(:hq, @tag)
    else
      render 'edit'
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to hq_tags_path, notice: "Post Deleted"
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end


end

app/controllers/hq/users_controller.rb
class Hq::UsersController < Hq::ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy, :toggle_is_active]
  add_breadcrumb I18n.t('activerecord.models.users'), :hq_users_path

  def index
    @search = User.order(id: :desc).search(params[:q])
    @users = @search.result(distinct: true).paginate(page: params[:page])
    respond_with(@users)
  end

  def show
    add_breadcrumb @user.name, hq_user_path(@user)
    respond_with(@user)
  end

  def new
    add_breadcrumb t('tooltips.new'), new_hq_user_path
    @user = User.new
    respond_with(@user)
  end

  def edit
    add_breadcrumb @user.name, hq_user_path(@user)
    add_breadcrumb t('tooltips.edit'), edit_hq_user_path
  end

  def create
    @user = User.new(user_params)
    @user.save
    respond_with(:hq, @user)
  end

  def update
    @user.update(user_params)
    respond_with(:hq, @user)
  end

  def destroy
    @user.destroy
    respond_with(:hq, @user, location: request.referer)
  end

  def toggle_is_active
    if @user.update( is_active: !@user.is_active )
      @user.is_active ?
          flash[:info] = t('flash.actions.toggle_is_active.active', resource_name: User.model_name.human) :
          flash[:info] = t('flash.actions.toggle_is_active.passive', resource_name: User.model_name.human)
    else
      flash[:danger] = t('flash.messages.error_occurred')
    end
    respond_with(:hq, @user, location: request.referer)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :name, :surname, :time_zone)
  end
end

app/controllers/user/carts_controller.rb
class User::CartsController < User:: ApplicationController
  before_action :get_cart, only: %i[show destroy]

  def create
    @cart = Cart.new(cart_params)
    @cart.save
  end

  def show
    @cart_items = CartItem.where(cart_id: @cart.id)
    @cart_items.each { |ci| @cart.total_price += ci.product.price }
  end

  private
  def get_cart
    @cart = Cart.find(params[:id])
  end
  def cart_params
    params.require(:cart).permit(:user_id)
  end
end

app/controllers/user/dashboard_controller.rb
class User::DashboardController < User::UserApplicationController

  add_breadcrumb I18n.t('dock.dashboard'), :user_dashboard_index_path

  def index
  end

end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # layout 'user/login'

  private

  def after_resetting_password_path_for(resource)
    user_root_path
  end

end

app/controllers/user/profile_controller.rb
class User::ProfileController < User::UserApplicationController

  before_action :set_profile, only: [:show, :edit, :update]
  add_breadcrumb I18n.t('dock.profile'), :user_profile_path

  def show
    add_breadcrumb @profile.full_name, user_profile_path
    respond_with(:user, @profile)
  end

  def edit
    add_breadcrumb t('tooltips.edit'), edit_user_profile_path
  end

  def update
    @profile.update(profile_params)
    respond_with(:user, @profile, location: user_profile_path)
  end

  private

  def set_profile
    @profile = current_user
  end

  def profile_params
    params.require(:user)
      .permit(
        :name,
        :surname,
        :time_zone
    )
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  # layout 'user/application'
  before_action :authenticate_user!, except: [:new, :create]
  before_action :redirect_user, only: [:destroy]
  add_breadcrumb I18n.t('activerecord.models.user'), :user_root_path

  def edit
  end

  private

  def redirect_user
    redirect_to user_root_path
  end

  def after_update_path_for(resource)
    user_root_path
  end

end

app/views/hq/users/_blank.html.haml
- if params[:q].present?
  = render 'list'
- else
  .alert.alert-warning
    %p
      %h3= t('view.there_is_no_data', resource: User.model_name.human.downcase)
      = link_to new_hq_user_path, class: 'btn btn-primary' do
        = t('action_button.new', resource_name: User.model_name.human)
        = t('btn.add')

app/views/hq/users/_filters.html.haml
.table-header.row
  .col-lg-3
    = link_to hq_users_path(q: {is_active_true: 1}), class: 'btn btn-success' do
      = t('view.active')
      %span.badge= User.where(is_active: true).count
    = link_to hq_users_path(q: {is_active_false: 1}), class: 'btn btn-warning' do
      = t('view.passive')
      %span.badge= User.where(is_active: false).count
    - if params[:q].present? && (params[:q][:is_active_true].present? || params[:q][:is_active_false].present? || params[:q][:name_or_surname_cont].present?)
      = link_to hq_users_path, class: 'btn btn-info' do
        = t('view.all')
        %span.badge= User.count
  .col-lg-9
    = search_form_for [:hq, @search], builder: SimpleForm::FormBuilder, html: {class: 'form-inline', data: { turboform: true }} do |f|
      .pull-right
        .input-group
          = f.input_field :name_or_surname_cont, label: false, class: 'form-control', placeholder: t('view.quick_search')
          %span.input-group-btn
            = button_tag( class: 'btn btn-primary') do
              %i.icon-search

app/views/hq/users/_form.html.haml
.panel.panel-default
  .panel-heading
    %i.icon-edit.icon-large
    = yield :form_title
  .panel-body
    = simple_form_for([:hq, @user], validate: true) do |f|
      = f.error_notification

      .form-inputs
        = f.input :name
        = f.input :surname
        = f.input :email
        = f.input :time_zone, input_html: { class: 'chosen-select'}, include_blank: t('view.select')

      .form-actions
        - text = @user.id.present? ? t('btn.update') : t('btn.add')
        = f.button :submit, text, class: 'btn btn-primary'
        = link_to t('cancel'), hq_users_path, class: 'btn'

app/views/hq/users/_list.html.haml
.panel-body.filters
  = render 'filters'
%table.table
  %thead
    %tr
      %th= sort_link(@search, :id, t('activerecord.attributes.user.id'))
      %th= sort_link(@search, :name, t('activerecord.attributes.user.name'))
      %th= sort_link(@search, :email, t('activerecord.attributes.user.email'))
      %th= sort_link(@search, :current_sign_in_at, t('activerecord.attributes.user.current_sign_in_at'))
      %th= sort_link(@search, :last_sign_in_at, t('activerecord.attributes.user.last_sign_in_at'))
      %th= sort_link(@search, :is_active, t('activerecord.attributes.user.is_active'))
      %th.actions
        = t('view.actions')
  %tbody.users
    = render @users

app/views/hq/users/_user.html.haml
%tr{class: user.is_active ? 'active' : 'passive'}
  %td= user.id
  %td= user.full_name
  %td= mail_to user.email, user.email
  %td=l user.current_sign_in_at if user.current_sign_in_at.present?
  %td=l user.last_sign_in_at if user.last_sign_in_at.present?
  %td= user.is_active ? t('view.active') : t('view.passive')
  %td.action
    = link_to([:hq, user], class: 'btn btn-success', data: { toggle: :tooltip}, title: t('tooltips.zoom')) do
      %i.icon-zoom-in
    = link_to(edit_hq_user_path(user) , class: 'btn btn-info', data: { toggle: :tooltip }, title: t('tooltips.edit')) do
      %i.icon-edit
    = link_to([:hq, user], class: 'btn btn-danger', method: :delete, data: { confirm: t('tooltips.are_you_sure'), toggle: :tooltip }, title: t('tooltips.delete')) do
      %i.icon-trash
    - if user.is_active
      = link_to(toggle_is_active_hq_user_path(user), class: 'btn btn-danger', method: :post, data: { toggle: :tooltip}, title: t('view.make_passive') ) do
        %i.icon-ban-circle
    - else
      = link_to(toggle_is_active_hq_user_path(user), class: 'btn btn-info', method: :post, data: { toggle: :tooltip}, title: t('view.make_active')) do
        %i.icon-check

app/views/hq/users/edit.html.haml
- content_for :form_title do
  = t('tt.edit', resource_name: 'Yönetici bilgilerini')
= render 'form'

app/views/hq/users/index.html.haml
- content_for :toolbar do
  = link_to new_hq_user_path, class: 'btn btn-default' do
    %i.icon-plus
    = t('action_button.new', resource_name: User.model_name.human)

.panel.panel-default.grid
  .panel-heading
    %i.fa.fa-table.icon-large
    = t('activerecord.models.users')
    .panel-tools
      .btn-group
        %a.btn{href: hq_users_path, data: {toggle: 'toolbar-tooltip'}, title: t('view.reload')}
          %i.fa.fa-refresh
      .badge= @users.total_entries
  =blankable(@users)
  .panel-footer
    .pagination.pagination-sm
      = will_paginate @users, renderer: BootstrapPagination::Rails, bootstrap: 3

app/views/hq/users/new.html.haml
- content_for :form_title do
  = t('tt.new', resource_name: User.model_name.human)
.alert.alert-info
  = t('view.create_resource_mail_info', resource: User.model_name.human.downcase)
= render 'form'

app/views/hq/users/show.html.haml
- content_for :toolbar do
  = link_to edit_hq_user_path(@user ), class: 'btn btn-default' do
    %i.icon-pencil
    = t('action_button.edit')
.panel.panel-default
  .panel-heading
    %i.icon-edit.icon-large
    = t('tt.show', resource_name: User.model_name.human)
  .panel-body
    = show_for @user do |s|
      = s.attribute :name
      = s.attribute :surname
      = s.attribute :email do
        = mail_to @user.email, @user.email
      = s.attribute :is_active
      = s.attribute :time_zone
      = s.attribute :current_sign_in_at
      = s.attribute :last_sign_in_at
      = s.attribute :created_at
      = s.attribute :updated_at